# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required
language: R
cache: packages
services:
  - docker

before_install:
  - docker pull selenium/standalone-firefox:2.53.0
  - docker run -d -p 127.0.0.1:4444:4444 selenium/standalone-chrome:2.53.0
r:
  - oldrel
  - release
  - devel

after_success:
- Rscript -e 'covr::codecov()'
