# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required
language: R
cache: packages
services:
  - docker
env:
  - NOT_CRAN=true

before_install:
  - docker pull selenium/standalone-firefox:2.53.0
  - docker run -d -p 127.0.0.1:4444:4444 selenium/standalone-chrome:2.53.0
  - svn checkout https://github.com/SeleniumHQ/selenium/trunk/common/src/web
  - npm install http-server -g
  - http-server web -p 3000&

r:
  - oldrel
  - release
  - devel

after_success:
- Rscript -e 'covr::codecov()'
