sudo: required
language: R
cache: packages
r_github_packages:
- johndharrison/seleniumPipes
services:
- docker
addons:
  sauce_connect: true
env:
  matrix:
  - NOT_CRAN=true
  global:
  - secure: eppSocqIqALXo5VtKPR1yiBx7LcN1rS8jFxghAxfRpczSJO22xPZtumJw91iTKvZ5vYSI4Y7klP9curF7mMFkfO0tLmqiBoZUMjmBnVytd8XKejpRW1EyTFi+aelNxVm95MXsszn/m4oCwbBxXB8g7dSCy0qOkcaYYri6hxflU9u7+OxLxZdl00VvZbhSF/7YJom0myBTqXHxtJbzPX5PomTzoSnhtTlEMpz2JcRGne581VYvaO5ZbHMlzZPfVeAiZyLEnDIdCARwSQQ2iK9Sfa89Kva+e7Nn1iz8ImLhFz7EA6mHdvTCONi3pZIq7zX4M4wNNx/+/GOS6STLZkArapGFWofAfR1MbzE+EBHla7Zt/N4sG97TapQR8Yy3LGceWdIAZXKljOTyyA+8PoTH8RoaeBOaluinLU4Ej10vIIJPbj330D6qReg5ek9Xmad0/oBRxsxSyE94OmG2E8kwykTWRvQAi/2Wz+v4gGDpZhZHP0bkS4g8BN0oLc1uX5fw+4L083LLNt9Fvx4/fOU3hjaRVLl/tjJRruMfMdUNfcPLqpVvi2t3i0AjJavJT+8wYTKWcN8RwniQFYQaqpeKrK4NeDa3eG8ospPcr9+DszNkWcU7TWTEkVTR8Tuwpb+KOmSqzL1OijY70UaMeuCc5Mp2IvhHef/kziSkcMaBaQ=
  - secure: az0ghI7UwdpgzUQabtmoEKyUOf9z/QzT9GiDbZBFwEUn7+cDX+mJ/2GLXj+All9lrDxhaB7h6Ur25OlePynBSI0w6UHJy9IFw30gTVfRY3B1QobCDa0Wbp17xEb1UGyKRB8VOsHWwAlCDwRUuHIwDahtoAQBYBxMJNOf6eQ/2zgAUDOG4ovJMUKBEl+jw/gecJClnXGUINPaXx4cHnHMFCCoMD2FmNX64+2wxsITiitoxexqLhCxisXZkkIlqVam3MN1cOgRcE28y5AUQaJuM6uMWiesmipc62bjBm+2VK09a6HZ+MQApBZTel1RoXGoG1OOk0pLcKLvXw3T9rEEO4gy2Rph29e/jIJ5JOrqbLA5kDc7FgU8FWzJzdXI/M/qqzbWCPn257pokfx8hnELfNPr+Uyf2HfKSZmjwez7XbLuA/oQnJhhywgif3VFGfHY1l2tEQedRoutOJAgHjnGZS57McZKrOWEs/bXH6haCo5N2OcAMSl0sUNT5zpJUtVd8QaSl+LD3Dlw3/MPop/66awJLn5J5ERIB6VEJx0ao7OKA55ILKbmYmdUbn0rNVOf3HhTUz3G/BGtxMxt/C4JWzrS8WlejAXnnG3TB5iS27n3rew43M1Ny42K3d/nP/8CFu1yHBPx5/EvqXEU+NPLHeBNxZdYhqBxEpWeqwGxizQ=
before_install:
- svn checkout https://github.com/SeleniumHQ/selenium/trunk/common/src/web
- docker run -d -p 3000:8080 --name http-server -v $(pwd)/web:/public redsadic/docker-http-server&
- docker run -d -p 127.0.0.1:4444:4444 --link http-server selenium/standalone-chrome:2.53.1
r:
- oldrel
- release
- devel
after_success:
- Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R", "R/oldMethods.R"))'
- git log -n 1 --format=%B | grep -iq "SAUCETESTUPDATE"; if [ $? -eq 0 ]; then echo
  "Updating SauceLab browser tests"; Rscript -e 'library(seleniumPipes); source(file.path(find.package("seleniumPipes"), "Saucetests", "runtest.R"))'; fi
